(package-install 'exec-path-from-shell)
(package-install 'color-theme)
(package-install 'anzu)
(package-install 'auto-complete)
(package-install 'auto-highlight-symbol)
(package-install 'popwin)

(package-install 'magit)
(package-install 'flycheck)

(package-install 'jedi)
(package-install 'js2-mode)
(package-install 'go-mode)
(package-install 'go-eldoc)
(package-install 'go-autocomplete)
(package-install 'php-mode)
(package-install 'web-mode)

(package-install 'yatex)
(package-install 'yaml-mode)
(package-install 'markdown-mode)
